name: publish
on: [push]
jobs:
publish-railinventory-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the railinventory docker image
run: |
       docker build . --tag ghcr.io/jonas-luetolf/railinventory
